// NEXT
import Head from "next/head";

// Components
import NavBar from "../components/NavBar";

const Home = () => {
  return (
    <div>
      <Head>
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Generated by create next app" />
        <meta name="keywords" content="Yogesh, Samsi, Tabla, Maestro, Allarakha, Abbaji, Tabla Player" />
        <title>Home | Yogesh Samsi</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar bg="dark-30" />
      <main></main>
    </div>
  );
};

export default Home;
