// NEXT
import Head from "next/head";

// Components
import NavBar from "../components/NavBar";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Home | Yogesh Samsi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar />
      <main></main>
    </div>
  );
};

export default Home;
